export const SET_TARGET = "SET_TARGET";
export const SET_IN_PROGRESS = "SET_IN_PROGRESS";
export const SET_WINNER_NODE = "SET_WINNER_NODE";
export const SET_HIGHEST_FUNDS_INDEX = "SET_HIGHEST_FUNDS_INDEX";
export const SET_NODES = "SET_NODES";
export const SET_NONCE = "SET_NONCE";
export const SET_BLOCKS = "SET_BLOCKS";
export const SET_TRANSACTIONS = "SET_TRANSACTIONS";